In [3]:
#Checking versions of each library

import pandas as pd
import numpy as np
import sklearn

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Scikit-learn version:", sklearn.__version__)

Pandas version: 3.0.3
NumPy version: 2.4.6
Scikit-learn version: 1.9.0

In [4]:
#Performing small test load first 5 rows of the dataset

from pathlib import Path

data_file = Path("/Users/kevinvillon/Desktop/NOVA_IT691/data/cicids2017_cleaned_WHOLE_SET.csv")
#please remember to change the path within the quotes corresponding to where the file is in your device

sample_df = pd.read_csv(data_file, nrows=5000)

sample_df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Length of Fwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,...,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Max,Active Min,Idle Mean,Idle Max,Idle Min,Attack Type
0,22,1266342,41,2664,456,0,64.975610,109.864573,976,0,...,243,24,32,0.0,0,0,0.0,0,0,Normal Traffic
1,22,1319353,41,2664,456,0,64.975610,109.864573,976,0,...,243,24,32,0.0,0,0,0.0,0,0,Normal Traffic
2,22,160,1,0,0,0,0.000000,0.000000,0,0,...,243,0,32,0.0,0,0,0.0,0,0,Normal Traffic
3,22,1303488,41,2728,456,0,66.536585,110.129945,976,0,...,243,24,32,0.0,0,0,0.0,0,0,Normal Traffic
4,35396,77,1,0,0,0,0.000000,0.000000,0,0,...,290,0,32,0.0,0,0,0.0,0,0,Normal Traffic

In [5]:
#Inspecting the clean dataset

print("Rows and columns in sample:", sample_df.shape)

print("\nColumn names:")
print(sample_df.columns.tolist())

Rows and columns in sample: (5000, 53)

Column names:
['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Length of Fwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'Average Packet Size', 'Subflow Fwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Max', 'Idle Min', 'Attack Type']

In [6]:
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 53 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Destination Port             5000 non-null   int64
 1   Flow Duration                5000 non-null   int64
 2   Total Fwd Packets            5000 non-null   int64
 3   Total Length of Fwd Packets  5000 non-null   int64
 4   Fwd Packet Length Max        5000 non-null   int64
 5   Fwd Packet Length Min        5000 non-null   int64
 6   Fwd Packet Length Mean       5000 non-null   float64
 7   Fwd Packet Length Std        5000 non-null   float64
 8   Bwd Packet Length Max        5000 non-null   int64
 9   Bwd Packet Length Min        5000 non-null   int64
 10  Bwd Packet Length Mean       5000 non-null   float64
 11  Bwd Packet Length Std        5000 non-null   float64
 12  Flow Bytes/s                 5000 non-null   float64
 13  Flow Packets/s               5000 non-null   float64
 14  Flow IAT Mean                5000 non-null   float64
 15  Flow IAT Std                 5000 non-null   float64
 16  Flow IAT Max                 5000 non-null   int64
 17  Flow IAT Min                 5000 non-null   int64
 18  Fwd IAT Total                5000 non-null   int64
 19  Fwd IAT Mean                 5000 non-null   float64
 20  Fwd IAT Std                  5000 non-null   float64
 21  Fwd IAT Max                  5000 non-null   int64
 22  Fwd IAT Min                  5000 non-null   int64
 23  Bwd IAT Total                5000 non-null   int64
 24  Bwd IAT Mean                 5000 non-null   float64
 25  Bwd IAT Std                  5000 non-null   float64
 26  Bwd IAT Max                  5000 non-null   int64
 27  Bwd IAT Min                  5000 non-null   int64
 28  Fwd Header Length            5000 non-null   int64
 29  Bwd Header Length            5000 non-null   int64
 30  Fwd Packets/s                5000 non-null   float64
 31  Bwd Packets/s                5000 non-null   float64
 32  Min Packet Length            5000 non-null   int64
 33  Max Packet Length            5000 non-null   int64
 34  Packet Length Mean           5000 non-null   float64
 35  Packet Length Std            5000 non-null   float64
 36  Packet Length Variance       5000 non-null   float64
 37  FIN Flag Count               5000 non-null   int64
 38  PSH Flag Count               5000 non-null   int64
 39  ACK Flag Count               5000 non-null   int64
 40  Average Packet Size          5000 non-null   float64
 41  Subflow Fwd Bytes            5000 non-null   int64
 42  Init_Win_bytes_forward       5000 non-null   int64
 43  Init_Win_bytes_backward      5000 non-null   int64
 44  act_data_pkt_fwd             5000 non-null   int64
 45  min_seg_size_forward         5000 non-null   int64
 46  Active Mean                  5000 non-null   float64
 47  Active Max                   5000 non-null   int64
 48  Active Min                   5000 non-null   int64
 49  Idle Mean                    5000 non-null   float64
 50  Idle Max                     5000 non-null   int64
 51  Idle Min                     5000 non-null   int64
 52  Attack Type                  5000 non-null   str
dtypes: float64(20), int64(32), str(1)
memory usage: 2.1 MB

In [9]:
sample_df.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Length of Fwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,...,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Max,Active Min,Idle Mean,Idle Max,Idle Min
count,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,...,5000.000000,5000.000000,5000.00000,5000.000000,5.000000e+03,5.000000e+03,5.000000e+03,5.000000e+03,5.000000e+03,5.000000e+03
mean,5958.887600,1.091736e+07,6.876200,458.524800,152.87720,24.937000,49.987373,43.657263,370.18320,58.333400,...,4583.137400,1600.786400,4.25500,24.621600,8.726722e+04,1.994803e+05,5.856047e+04,2.781493e+06,2.827917e+06,2.716515e+06
std,15878.119923,3.007406e+07,26.884111,1659.386382,388.93406,38.582757,93.496490,135.002548,781.98132,77.263089,...,10943.648222,7593.415777,21.46319,6.024091,5.398330e+05,1.099330e+06,4.924633e+05,1.040970e+07,1.053031e+07,1.033967e+07
min,0.000000,1.000000e+00,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,...,-1.000000,-1.000000,0.00000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,53.000000,1.880000e+02,1.000000,40.000000,28.00000,0.000000,18.500000,0.000000,6.00000,0.000000,...,-1.000000,-1.000000,0.00000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,53.000000,3.123600e+04,2.000000,68.000000,42.00000,29.000000,39.000000,0.000000,89.00000,47.000000,...,-1.000000,-1.000000,1.00000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,443.000000,3.175702e+05,4.000000,152.000000,59.00000,43.000000,50.000000,5.311328,174.25000,101.000000,...,4380.000000,237.000000,3.00000,32.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,64253.000000,1.199989e+08,651.000000,34076.000000,6145.00000,1472.000000,1650.428571,2117.661545,4757.00000,1442.000000,...,65535.000000,65535.000000,634.00000,44.000000,9.826595e+06,2.580000e+07,9.826595e+06,1.130000e+08,1.130000e+08,1.130000e+08

In [11]:
# Checking if Missing values were corrected
sample_df.isnull().sum().sort_values(ascending=False).head(20)

Destination Port           0
Bwd IAT Min                0
Bwd Header Length          0
Fwd Packets/s              0
Bwd Packets/s              0
Min Packet Length          0
Max Packet Length          0
Packet Length Mean         0
Packet Length Std          0
Packet Length Variance     0
FIN Flag Count             0
PSH Flag Count             0
ACK Flag Count             0
Average Packet Size        0
Subflow Fwd Bytes          0
Init_Win_bytes_forward     0
Init_Win_bytes_backward    0
act_data_pkt_fwd           0
min_seg_size_forward       0
Active Mean                0
dtype: int64

In [12]:
# Checking if Duplicate rows were corrected
sample_df.duplicated().sum()

np.int64(0)

In [13]:
# Checking if Infinite values in numeric columns were corrected
numeric_data = sample_df.select_dtypes(include=np.number)

np.isinf(numeric_data).sum().sort_values(ascending=False).head(20)

Destination Port           0
Flow Duration              0
Fwd Header Length          0
Bwd Header Length          0
Fwd Packets/s              0
Bwd Packets/s              0
Min Packet Length          0
Max Packet Length          0
Packet Length Mean         0
Packet Length Std          0
Packet Length Variance     0
FIN Flag Count             0
PSH Flag Count             0
ACK Flag Count             0
Average Packet Size        0
Subflow Fwd Bytes          0
Init_Win_bytes_forward     0
Init_Win_bytes_backward    0
act_data_pkt_fwd           0
min_seg_size_forward       0
dtype: int64